/* Course definitions: u2 perimeter/area concepts and formulas. */
'use strict';
(() => {
 const M={boundary:'M-U2-MEANING-01',surface:'M-U2-MEANING-02',compareNumber:'M-U2-MEANING-03',formulaSwap:'M-U2-FORMULA-01',unit:'M-U2-FORMULA-02'};
 const O={meaning:'O-U2-MEANING-01',representation:'O-U2-MEANING-02',explain:'O-U2-MEANING-03',formulaP:'O-U2-FORMULA-01',formulaA:'O-U2-FORMULA-02',transfer:'O-U2-FORMULA-03'};
 const five=(a,b,c,d)=>['',a,b,c,d];
 const meaning={schemaVersion:'0.2',flowId:'u2.meaning.v2',flowVersion:'0.1.0',courseId:'sujiao-math-2026',unitId:'u2',nodeId:'meaning',initialStep:'diagnoseFence',steps:{
  diagnoseFence:{objectiveId:O.meaning,hints:five('先问：测的是边，还是里面的一整块？','“围着花坛走一圈”只经过边界。','边界一周的长度叫周长。','所以围栏、跑一圈、框边通常对应周长。'),view:({renderers})=>({title:'先分清：量的是“边”还是“面”？',prompt:'给一个长5米、宽3米的花坛装一圈围栏。我们要测量什么？',choices:[['perimeter','边界一圈的长度'],['area','里面平面的大小']],visual:renderers.rect({w:5,h:3,mode:'perimeter',label:'长方形花坛边界'})}),transitions:[{when:'perimeter',to:'diagnoseGrass',effects:[{type:'markObjective',stage:'diagnostic_success'}]},{when:'area',to:'repairBoundary',lane:'repair',effects:[{type:'markMisconception',id:M.boundary,confidence:'high'}]}]},
  repairBoundary:{objectiveId:O.meaning,hints:five('手指沿红线走一圈。','围栏只安装在四周，不铺在里面。','四条边首尾相接形成一周。','这里测的是边界长度，所以是周长。'),view:({renderers})=>({title:'只修“边界”这个概念',prompt:'围栏只装在花坛四周。红线表示围栏经过的位置，它描述的是？',choices:[['perimeter','边界长度'],['area','平面大小']],visual:renderers.rect({w:5,h:3,mode:'perimeter'})}),transitions:[{when:'perimeter',to:'diagnoseGrass',lane:'standard',effects:[{type:'resolveMisconception',id:M.boundary},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.boundary}},{type:'scheduleReview',reason:'concept_repair'}]}]},
  diagnoseGrass:{objectiveId:O.meaning,hints:five('这次不是围边，而是要把里面全部覆盖。','覆盖多少地面关注的是“面”。','面积描述平面有多大。','铺草坪、铺地砖、刷墙面通常对应面积。'),view:({renderers})=>({title:'换一个任务：铺满里面',prompt:'如果要给这个5米×3米的花坛全部铺草坪，我们要测量什么？',choices:[['area','里面平面的大小'],['perimeter','边界一圈的长度']],visual:renderers.rect({w:5,h:3,mode:'area',label:'长方形花坛内部平面'})}),transitions:[{when:'area',to:'contrastSameNumber',effects:[{type:'markObjective',objectiveId:O.representation,stage:'guided_success'}]},{when:'perimeter',to:'repairSurface',lane:'repair',effects:[{type:'markMisconception',id:M.surface,confidence:'high'}]}]},
  repairSurface:{objectiveId:O.meaning,hints:five('想象把小方砖铺满整个内部。','铺满需要覆盖的是二维平面。','数单位方格是在测面积。','所以铺草坪对应面积，不是周长。'),view:({renderers})=>({title:'只修“平面”这个概念',prompt:'蓝色小方格铺满整个内部。这个数量描述的是？',choices:[['area','面积'],['perimeter','周长']],visual:renderers.rect({w:5,h:3,mode:'area'})}),transitions:[{when:'area',to:'contrastSameNumber',lane:'standard',effects:[{type:'resolveMisconception',id:M.surface},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.surface}}]}]},
  contrastSameNumber:{objectiveId:O.explain,hints:five('不要只看数字16，要看它在量什么。','一个是长度单位，一个是面积单位。','4×4正方形：周长16厘米，面积16平方厘米。','数字一样不代表数学量一样；单位和意义决定它们是什么。'),view:({renderers})=>({title:'数字一样，意义也一样吗？',prompt:'边长4厘米的正方形：周长是16厘米，面积是16平方厘米。下面哪句话正确？',choices:[['different','数字相同，但表示不同的量，不能说周长等于面积'],['same','都是16，所以周长等于面积']],visual:renderers.rect({w:4,h:4,mode:'both',label:'边长4的正方形同时显示边界和内部'})}),transitions:[{when:'different',to:'formalize',effects:[{type:'emit',event:'EXPLANATION_PASS',result:{independent:true}},{type:'markObjective',objectiveId:O.explain,stage:'independent_success'}]},{when:'same',to:'repairCompare',lane:'repair',effects:[{type:'markMisconception',id:M.compareNumber,confidence:'high'}]}]},
  repairCompare:{objectiveId:O.explain,hints:five('给两个16分别带上单位再读。','16厘米是长度；16平方厘米是面积。','单位不同说明量的种类不同。','数值碰巧相等，不代表周长和面积是同一个量。'),view:{title:'给数字带上“身份”',prompt:'16厘米和16平方厘米最关键的区别是什么？',choices:[['unit','单位不同，表示的数学量不同'],['number','数字都是16，所以完全相同']]},transitions:[{when:'unit',to:'formalize',lane:'standard',effects:[{type:'resolveMisconception',id:M.compareNumber},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.compareNumber}}]}]},
  formalize:{objectiveId:O.explain,hints:five('分别抓住“边界”和“平面”两个关键词。','周长：边界一周的长度；面积：平面的大小。','长度常用厘米、米；面积常用平方厘米、平方米。','完整规律要同时包含测量对象和单位类型。'),view:{title:'现在把概念说完整',prompt:'哪一句最准确？',choices:[['rule','周长量边界一周的长度；面积量平面的大小；它们使用不同类型的单位'],['swap','周长量里面，面积量外边'],['number','只要数值相同，就可以互相比较大小']]},transitions:[{when:'rule',to:'transfer',effects:[{type:'setFlag',key:'formalized',value:true},{type:'emit',event:'FORMALIZATION_UNLOCKED',result:{rule:'boundary-vs-surface'}},{type:'markObjective',stage:'guided_success'}]}]},
  transfer:{objectiveId:O.meaning,hints:five('先问工人实际要处理的是哪里。','贴踢脚线沿房间四周；铺地板覆盖整个地面。','沿边→周长；铺面→面积。','两个任务分别对应周长和面积。'),view:{title:'迁移到真实任务',prompt:'装修房间时，“买踢脚线”和“买地板”分别主要需要哪个量？',choices:[['pa','踢脚线看周长；地板看面积'],['ap','踢脚线看面积；地板看周长'],['pp','两个都只看周长']]},transitions:[{when:'pa',to:'complete',effects:[{type:'emit',event:'TRANSFER_PASS',result:{independent:true}},{type:'markObjective',stage:'transfer_success'}]}]},
  complete:{objectiveId:O.meaning,hints:['','','','',''],reviewOnH4:false,view:{title:'边和面已经分清了',prompt:'以后先问“任务发生在边界，还是覆盖整个平面”，再决定用周长还是面积。',choices:[]},transitions:[]}
 }};
 const formula={schemaVersion:'0.2',flowId:'u2.formula.v2',flowVersion:'0.1.0',courseId:'sujiao-math-2026',unitId:'u2',nodeId:'formula',initialStep:'derivePerimeter',steps:{
  derivePerimeter:{objectiveId:O.formulaP,hints:five('沿四条边依次相加。','长方形有两条长、两条宽。','5＋3＋5＋3可以整理。','周长=(长+宽)×2。'),view:({renderers})=>({title:'公式先别背：从四条边长出来',prompt:'长5厘米、宽3厘米的长方形，沿边界走一圈。哪个算式最直接体现“四条边”？',choices:[['sum','5＋3＋5＋3'],['area','5×3'],['half','5＋3']],visual:renderers.sideSum(5,3)}),transitions:[{when:'sum',to:'compressPerimeter',effects:[{type:'markObjective',stage:'guided_success'}]},{when:'area',to:'repairFormula',lane:'repair',effects:[{type:'markMisconception',id:M.formulaSwap,confidence:'high'}]}]},
  repairFormula:{objectiveId:O.formulaP,hints:five('5×3是在数几行几列。','周长必须把四条边都包含进去。','两条长+两条宽。','5＋3＋5＋3才描述边界一圈。'),view:({renderers})=>({title:'区分“沿边”和“铺格”',prompt:'现在只沿红色边界走一圈，应该使用哪种关系？',choices:[['sum','把四条边加起来'],['multiply','长×宽']],visual:renderers.rect({w:5,h:3,mode:'both'})}),transitions:[{when:'sum',to:'compressPerimeter',lane:'standard',effects:[{type:'resolveMisconception',id:M.formulaSwap},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.formulaSwap}},{type:'scheduleReview',reason:'formula_swap'}]}]},
  compressPerimeter:{objectiveId:O.formulaP,hints:five('把相同的两条长、两条宽配对。','5＋3＋5＋3=(5＋3)×2。','括号里是一条长加一条宽，也叫半周长。','长方形周长=(长+宽)×2。'),view:{title:'把四边相加压缩成公式',prompt:'5＋3＋5＋3可以等价写成？',choices:[['p','(5＋3)×2'],['a','5×3'],['wrong','5＋3×2']]},transitions:[{when:'p',to:'deriveArea',effects:[{type:'markObjective',stage:'independent_success'}]}]},
  deriveArea:{objectiveId:O.formulaA,hints:five('面积看铺满内部需要多少单位方格。','每行5格，共3行。','相同加数5连续出现3次，可写成5×3。','长方形面积=长×宽。'),view:({renderers})=>({title:'面积公式也从方格长出来',prompt:'内部每行5个1平方厘米方格，一共3行。面积怎样算？',choices:[['a','5×3'],['p','(5＋3)×2'],['edge','5＋3＋5＋3']],visual:renderers.tileRows(5,3)+renderers.rect({w:5,h:3,mode:'area'})}),transitions:[{when:'a',to:'formalize',effects:[{type:'markObjective',stage:'independent_success'}]},{when:'p',to:'repairArea',lane:'repair',effects:[{type:'markMisconception',id:M.formulaSwap,confidence:'high'}]}]},
  repairArea:{objectiveId:O.formulaA,hints:five('现在数的是内部小方格。','每行格数×行数。','5格一行，有3行。','5×3=15平方厘米。'),view:({renderers})=>({title:'只看“铺满”这件事',prompt:'蓝色内部有3行，每行5格。应使用？',choices:[['a','5×3'],['p','(5＋3)×2']],visual:renderers.rect({w:5,h:3,mode:'area'})}),transitions:[{when:'a',to:'formalize',lane:'standard',effects:[{type:'resolveMisconception',id:M.formulaSwap},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.formulaSwap}}]}]},
  formalize:{objectiveId:O.explain,hints:five('一个公式处理边界，一个公式处理平面。','周长=(长+宽)×2；面积=长×宽。','别忘了对应单位：厘米 vs 平方厘米。','公式、测量对象、单位三者要配套。'),view:{title:'把对象、公式、单位配成一套',prompt:'哪一项全部匹配？',choices:[['rule','周长=(长+宽)×2，用长度单位；面积=长×宽，用面积单位'],['swap','周长=长×宽；面积=(长+宽)×2'],['unit','两个公式最后都用厘米']]},transitions:[{when:'rule',to:'transfer',effects:[{type:'setFlag',key:'formalized',value:true},{type:'emit',event:'FORMALIZATION_UNLOCKED',result:{rule:'rect-perimeter-area'}},{type:'markObjective',stage:'guided_success'}]},{when:'unit',to:'repairUnit',lane:'repair',effects:[{type:'markMisconception',id:M.unit,confidence:'high'}]}]},
  repairUnit:{objectiveId:O.explain,hints:five('看单位是不是在描述长度还是平面。','厘米是长度单位；平方厘米是面积单位。','面积公式的结果不是一条线的长度。','15平方厘米才是5×3长方形的面积单位。'),view:{title:'公式对了，单位也要对',prompt:'5厘米×3厘米的长方形，面积15后面应写？',choices:[['sq','平方厘米'],['cm','厘米']]},transitions:[{when:'sq',to:'transfer',lane:'standard',effects:[{type:'resolveMisconception',id:M.unit},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.unit}}]}]},
  transfer:{objectiveId:O.transfer,hints:five('先判断题目问边界还是覆盖面积。','围墙长度看周长；种草面积看面积。','长8宽4：周长24，面积32。','同一个长方形可以同时有周长和面积，但解决的是不同问题。'),view:({renderers})=>({title:'同一个图形，两种真实需求',prompt:'长8米、宽4米的长方形院子：围一圈围栏要多少米？铺满草坪要多少平方米？',choices:[['correct','24米；32平方米'],['swap','32米；24平方米'],['same','24米；24平方米']],visual:renderers.rect({w:8,h:4,mode:'both'})}),transitions:[{when:'correct',to:'complete',effects:[{type:'emit',event:'TRANSFER_PASS',result:{independent:true}},{type:'markObjective',stage:'transfer_success'}]}]},
  complete:{objectiveId:O.transfer,hints:['','','','',''],reviewOnH4:false,view:{title:'公式不再是孤立口诀',prompt:'先看任务发生在“边”还是“面”，再选择公式和单位。',choices:[]},transitions:[]}
 }};
 globalThis.AreaCourseDefinitions={meaning,formula,objectives:O,misconceptions:M};
})();
