/* Course definition: u3 / unit price, quantity and total price. */
'use strict';
(() => {
 const O={meaning:'O-U3-PRICE-01',total:'O-U3-PRICE-02',unit:'O-U3-PRICE-03',quantity:'O-U3-PRICE-04',composite:'O-U3-PRICE-05'};
 const M={unitMeaning:'M-U3-PRICE-01',addInsteadMultiply:'M-U3-PRICE-02',inverseRole:'M-U3-PRICE-03',skipSubtotal:'M-U3-PRICE-04'};
 const five=(a,b,c,d)=>['',a,b,c,d];
 const def={schemaVersion:'0.2',flowId:'u3.price.v2',flowVersion:'0.1.0',courseId:'sujiao-math-2026',unitId:'u3',nodeId:'price',initialStep:'diagnoseMeaning',steps:{
  diagnoseMeaning:{objectiveId:O.meaning,hints:five('先解释“每本8元”里的“每本”。','它描述的是1本对应的价格。','单价是“每1件”的价格，不是买了几件。','“每本8元”表示1本练习本8元。'),view:({renderers})=>({title:'先把“单价”说清楚',prompt:'“练习本每本8元”中的8元表示什么？',choices:[['unit','1本练习本的价格'],['total','买完所有练习本的总钱数'],['quantity','一共买8本']],visual:renderers.items({price:8,count:4,label:'练习本'})}),transitions:[{when:'unit',to:'deriveTotal',effects:[{type:'markObjective',stage:'diagnostic_success'}]},{when:'*',to:'repairMeaning',lane:'repair',effects:[{type:'markMisconception',id:M.unitMeaning,confidence:'high'}]}]},
  repairMeaning:{objectiveId:O.meaning,hints:five('只看一件商品上的价格标签。','每件都标8元，说明8元属于“一件”。','买几件是数量；所有钱合起来才是总价。','单价=每1件物品的价格。'),view:({renderers})=>({title:'只修“每1件”的意思',prompt:'图中每一本都标着8元。8元应该归到哪个量？',choices:[['unit','单价'],['quantity','数量'],['total','总价']],visual:renderers.items({price:8,count:4,label:'练习本'})}),transitions:[{when:'unit',to:'deriveTotal',lane:'standard',effects:[{type:'resolveMisconception',id:M.unitMeaning},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.unitMeaning}},{type:'scheduleReview',reason:'unit_price_meaning'}]}]},
  deriveTotal:{objectiveId:O.total,hints:five('把“8元”重复7次想一想。','相同单价重复7份，用乘法。','8+8+8+8+8+8+8=8×7。','单价×数量=总价，所以8×7=56元。'),view:({renderers})=>({title:'总价不是背公式，是相同单价重复累加',prompt:'每本8元，买7本。怎样表示总价最合适？',choices:[['mul','8×7'],['add','8＋7'],['div','8÷7']],visual:renderers.relation({unitValue:'8元/本',quantityValue:'7本',totalValue:'?'})}),transitions:[{when:'mul',to:'unknownUnit',effects:[{type:'markObjective',stage:'independent_success'}]},{when:'add',to:'repairMultiply',lane:'repair',effects:[{type:'markMisconception',id:M.addInsteadMultiply,confidence:'high'}]}]},
  repairMultiply:{objectiveId:O.total,hints:five('8和7不是同一种量，不能直接相加。','真正重复出现的是“8元”这一个单价。','7本意味着有7个8元。','所以用8×7，而不是8+7。'),view:({renderers})=>({title:'为什么不是8＋7？',prompt:'图里有7个相同的8元。哪个算式与图对应？',choices:[['mul','8×7'],['add','8＋7']],visual:renderers.items({price:8,count:7,label:'练习本'})}),transitions:[{when:'mul',to:'unknownUnit',lane:'standard',effects:[{type:'resolveMisconception',id:M.addInsteadMultiply},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.addInsteadMultiply}}]}]},
  unknownUnit:{objectiveId:O.unit,hints:five('现在总价和数量已知，缺的是“每1本多少元”。','把总价平均分给每一本。','56元对应7本，所以56÷7。','总价÷数量=单价。'),view:({renderers})=>({title:'同一个关系，换成求单价',prompt:'7本练习本共56元，每本多少元？',choices:[['divide','56÷7'],['multiply','56×7'],['other','7÷56']],visual:renderers.equalParts({total:56,count:7,label:'本'})}),transitions:[{when:'divide',to:'unknownQuantity',effects:[{type:'markObjective',stage:'independent_success'}]},{when:'multiply',to:'repairInverse',lane:'repair',effects:[{type:'markMisconception',id:M.inverseRole,confidence:'high'}]}]},
  repairInverse:{objectiveId:O.unit,hints:five('问的是“每一本”，要把总价分成若干相同份。','56元平均对应7本。','平均分用除法。','56÷7=8元/本。'),view:({renderers})=>({title:'总价要“分回”每一件',prompt:'56元是7本合起来的钱。求1本，应怎样做？',choices:[['divide','56÷7'],['multiply','56×7']],visual:renderers.equalParts({total:56,count:7,label:'本'})}),transitions:[{when:'divide',to:'unknownQuantity',lane:'standard',effects:[{type:'resolveMisconception',id:M.inverseRole},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.inverseRole}}]}]},
  unknownQuantity:{objectiveId:O.quantity,hints:five('现在已知每本6元和总价42元。','问“有几份6元”组成42元。','42÷6就是6元能取几份。','总价÷单价=数量，所以42÷6=7本。'),view:({renderers})=>({title:'再换一次：求数量',prompt:'每本6元，一共付42元。买了多少本？',choices:[['q','42÷6'],['m','42×6'],['a','42＋6']],visual:renderers.relation({unitValue:'6元/本',quantityValue:'?',totalValue:'42元'})}),transitions:[{when:'q',to:'formalize',effects:[{type:'markObjective',stage:'independent_success'}]}]},
  formalize:{objectiveId:O.meaning,hints:five('三种题其实是同一组数量关系。','已知单价和数量求总价用乘法。','已知总价和其中一个量，反求另一个量用除法。','单价×数量=总价；总价÷数量=单价；总价÷单价=数量。'),view:({renderers})=>({title:'三种问法，其实是一张关系图',prompt:'哪组关系全部正确？',choices:[['rule','单价×数量=总价；总价÷数量=单价；总价÷单价=数量'],['wrong','单价+数量=总价；总价×数量=单价'],['mix','单价×总价=数量']],visual:renderers.relation({unitValue:'单价',quantityValue:'数量',totalValue:'总价'})}),transitions:[{when:'rule',to:'composite',effects:[{type:'setFlag',key:'formalized',value:true},{type:'emit',event:'FORMALIZATION_UNLOCKED',result:{rule:'unit-price-quantity-total'}},{type:'markObjective',stage:'guided_success'}]}]},
  composite:{objectiveId:O.composite,hints:five('总价776元里包含两种商品的钱。','先求12盆芦荟用了多少元。','12×28=336元，剩下776-336=440元。','440元对应20盆吊兰，所以440÷20=22元/盆。'),view:({renderers})=>({title:'复合情境：先分离已知部分，再反求单价',prompt:'共花776元。12盆芦荟每盆28元，剩下的钱买20盆吊兰。吊兰每盆多少元？',choices:[['correct','先算12×28，再用(776－336)÷20'],['skip','直接776÷20'],['add','776＋336再÷20']],visual:renderers.budget({total:776,known:336,knownLabel:'12盆芦荟',unknownCount:20})}),transitions:[{when:'correct',to:'transfer',effects:[{type:'markObjective',stage:'independent_success'}]},{when:'skip',to:'repairComposite',lane:'repair',effects:[{type:'markMisconception',id:M.skipSubtotal,confidence:'high'}]}]},
  repairComposite:{objectiveId:O.composite,hints:five('776元不是全都用来买吊兰。','先把芦荟的钱从总价里拿出去。','12×28=336元。','剩440元买20盆吊兰，440÷20=22元/盆。'),view:({renderers})=>({title:'先问：776元全部属于吊兰吗？',prompt:'总价776元中，有336元已经属于芦荟。求吊兰单价前第一步应做什么？',choices:[['subtract','776－336'],['divide','776÷20'],['multiply','776×20']],visual:renderers.budget({total:776,known:336,knownLabel:'芦荟',unknownCount:20})}),transitions:[{when:'subtract',to:'transfer',lane:'standard',effects:[{type:'resolveMisconception',id:M.skipSubtotal},{type:'emit',event:'REPAIR_SUCCESS',result:{misconception_id:M.skipSubtotal}},{type:'scheduleReview',reason:'composite_price_model'}]}]},
  transfer:{objectiveId:O.composite,hints:five('先找“每个”的单位率，再看盒数和每盒个数。','7盒×6个=42个球。','84元对应42个球。','84÷42=2元/个。'),view:({renderers})=>({title:'迁移：单位从“盒”换成“个”',prompt:'7盒乒乓球，每盒6个，共84元。每个球多少元？',choices:[['correct','先算7×6=42个，再算84÷42'],['box','84÷7，只求每盒价格'],['wrong','84÷6']],visual:renderers.relation({unit:'每个球单价',quantity:'总个数',total:'总价',unitValue:'?',quantityValue:'7×6',totalValue:'84元'})}),transitions:[{when:'correct',to:'complete',effects:[{type:'emit',event:'TRANSFER_PASS',result:{independent:true}},{type:'markObjective',stage:'transfer_success'}]}]},
  complete:{objectiveId:O.composite,hints:['','','','',''],reviewOnH4:false,view:{title:'数量关系已经不是死公式',prompt:'先确定每1份是什么，再辨认单价、数量、总价；复合题先拆出属于当前关系的总价，再使用乘除互逆。',choices:[]},transitions:[]}
 }};
 globalThis.PriceCourseDefinition={definition:def,objectives:O,misconceptions:M};
})();
